# Generated by Django 3.1.7 on 2021-02-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210220_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='id_1',
            new_name='select1',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='id_2',
            new_name='select2',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='id_3',
            new_name='select3',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='id_4',
            new_name='select4',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='id_5',
            new_name='select5',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='id_6',
            new_name='select6',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='id_8',
            new_name='select7',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='id_7',
            new_name='select8',
        ),
        migrations.RemoveField(
            model_name='game',
            name='id_9',
        ),
        migrations.AddField(
            model_name='game',
            name='select9',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
