# Generated by Django 3.1.7 on 2021-02-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210220_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_over',
        ),
        migrations.RemoveField(
            model_name='game',
            name='select1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='select2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='select3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='select4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='select5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='select6',
        ),
        migrations.RemoveField(
            model_name='game',
            name='select7',
        ),
        migrations.RemoveField(
            model_name='game',
            name='select8',
        ),
        migrations.RemoveField(
            model_name='game',
            name='select9',
        ),
    ]
